name: Run Bash Script

on:
  push:
    branches:
      - main 
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Make scripts executable
      run: chmod +x bash-script/*.sh

    - name: Run Bash Script
      run: bash bash-script/syntax-checker.sh