name: Run Syntax Checker

on:
  push:
    branches:
      - main

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make scripts executable
      run: chmod +x bash-script/*.sh

    - name: Run Syntax Checker
      run: bash bash-script/syntax-checker-ga.sh
