name: Run Syntax Checker

on:
  push:
    branches:
      - main
      
jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for README.md
        run: |
          if [ ! -f README.md ]; then
            echo "README.md file is missing!"
            exit 1
          else
            echo "README.md file exists!"
          fi      
          
  check-syntax:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make scripts executable
      run: chmod +x bash-script/*.sh

    - name: Run Syntax Checker
      run: bash bash-script/syntax-checker-ga.sh
      
      
